/*
 * This file was automatically generated by EvoSuite
 * Tue Sep 22 12:45:00 GMT 2020
 */

package algorithm;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import algorithm.ActButtonListener;
import java.awt.event.ActionEvent;
import javax.swing.JTextArea;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class ActButtonListener_ESTest extends ActButtonListener_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      ActButtonListener actButtonListener0 = new ActButtonListener((JTextArea) null, (JTextArea) null);
      ActionEvent actionEvent0 = new ActionEvent("<L{;BeweRMy@G?", 0, "<L{;BeweRMy@G?");
      // Undeclared exception!
      try { 
        actButtonListener0.actionPerformed(actionEvent0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("algorithm.ActButtonListener", e);
      }
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      JTextArea jTextArea0 = new JTextArea();
      ActButtonListener actButtonListener0 = new ActButtonListener(jTextArea0, jTextArea0);
      ActionEvent actionEvent0 = new ActionEvent(actButtonListener0, (-1982439654), ".", (-1982439654));
      actButtonListener0.actionPerformed(actionEvent0);
      assertEquals((-1982439654), actionEvent0.getID());
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      JTextArea jTextArea0 = new JTextArea();
      ActButtonListener actButtonListener0 = new ActButtonListener(jTextArea0, jTextArea0);
      ActionEvent actionEvent0 = new ActionEvent(actButtonListener0, (-2273), "/", (-2273));
      actButtonListener0.actionPerformed(actionEvent0);
      assertEquals((-2273), actionEvent0.getModifiers());
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      JTextArea jTextArea0 = new JTextArea();
      ActButtonListener actButtonListener0 = new ActButtonListener(jTextArea0, jTextArea0);
      ActionEvent actionEvent0 = new ActionEvent("", (-1266), "x", (-1266));
      actButtonListener0.actionPerformed(actionEvent0);
      assertEquals(0L, actionEvent0.getWhen());
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      JTextArea jTextArea0 = new JTextArea();
      ActButtonListener actButtonListener0 = new ActButtonListener(jTextArea0, jTextArea0);
      ActionEvent actionEvent0 = new ActionEvent(jTextArea0, (-1952), "-", (-1952));
      actButtonListener0.actionPerformed(actionEvent0);
      assertEquals((-1952), actionEvent0.getID());
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      JTextArea jTextArea0 = new JTextArea();
      ActButtonListener actButtonListener0 = new ActButtonListener(jTextArea0, jTextArea0);
      ActionEvent actionEvent0 = new ActionEvent(jTextArea0, (-1266), "+", (-1266), (-1266));
      actButtonListener0.actionPerformed(actionEvent0);
      assertEquals((-1266L), actionEvent0.getWhen());
  }

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      JTextArea jTextArea0 = new JTextArea("=");
      ActButtonListener actButtonListener0 = new ActButtonListener(jTextArea0, jTextArea0);
      ActionEvent actionEvent0 = new ActionEvent("=", 648, "=", 2291L, (-2021232901));
      actButtonListener0.actionPerformed(actionEvent0);
      actButtonListener0.actionPerformed(actionEvent0);
      assertEquals((-2021232901), actionEvent0.getModifiers());
  }
}
