/*
 * This file was automatically generated by EvoSuite
 * Tue Sep 22 12:47:16 GMT 2020
 */

package algorithm;

import org.junit.Test;
import static org.junit.Assert.*;
import algorithm.Button;
import java.awt.Color;
import java.awt.Font;
import javax.swing.text.StyledEditorKit;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class Button_ESTest extends Button_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Button button0 = new Button();
      button0.setText("31+Z3mmb'.");
      assertFalse(button0.isFocusTraversalPolicyProvider());
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      Button button0 = new Button();
      Font font0 = new Font("uQ,$M&J_HCXysgB", 150, (-2717));
      StyledEditorKit.ForegroundAction styledEditorKit_ForegroundAction0 = new StyledEditorKit.ForegroundAction("", (Color) null);
      button0.changeSettings((Color) null, font0, styledEditorKit_ForegroundAction0);
      assertFalse(font0.isTransformed());
  }
}
